### ISSUE TITLE
Support faraday ~> 1.0

### ISSUE THREAD

**Issue by james1239090** [ably/ably-ruby-rest#11]
Hi

since faraday has updated the latest version 1.0.1

https://github.com/lostisland/faraday/releases

could we support faraday runtime_dependency to this version?

Thank you

**Comment by QuintinWillison** [comment]
Hello @james1239090 ... Thanks for letting us know. Can you describe what you're seeing with the current dependency configuration, please? We will look at this but I just want to make sure we understand the problem you are facing which requires a bump. Thanks!

**Comment by james1239090** [comment]
Hi

Thanks for the quick response

I have other gem required `faraday` ~> 1.0` in my Gemfile

Due to the add_runtime_dependency in here

https://github.com/ably/ably-ruby-rest/blob/main/ably-rest.gemspec

it only allows faraday version less than `1.0` base on the `'~> 0.12`

I'm not sure could we increase the ability to allow faraday version greater than 1.0

Thank you

**Comment by QuintinWillison** [comment]
Thanks for the explanation. I'm not a Ruby expert myself (by any margin! 😆) but I'll get someone who is to take a look.

**Comment by mattheworiordan** [comment]
Hey @james1239090 looking at https://github.com/lostisland/faraday/blob/master/UPGRADING.md#faraday-10, it seems there are some changes that would need to be checked before Faraday 1.0 support could be guaranteed.

I am running a build now https://travis-ci.org/github/ably/ably-ruby/builds/731430914, and will see what breaks.  Once I know what breaks, we can determine if it's a small change or not.

Bear with us please.

**Comment by mattheworiordan** [comment]
@james1239090 https://github.com/ably/ably-ruby/pull/205 should fix the issue, however if that works, we will need to release and then release a REST-only version too (this lib).  Are you able to test that everything works OK with the `ably-ruby` version first?

**Comment by QuintinWillison** [comment]
Hello @james1239090 - have you been able to validate @mattheworiordan's [branch](https://github.com/ably/ably-ruby/tree/faraday-1.0-support-test) yet?

**Comment by james1239090** [comment]
Hi, I’m sorry that I haven’t test it yet. I’ll test it at the end of this week, cheers.

**Comment by QuintinWillison** [comment]
Thanks @james1239090 - no need for Sorry! Just wanted to check in and see how you were getting on. We're keen to move this one along for you. 😁

**Comment by james1239090** [comment]
Hello, 

I have tested in my local env, looks good to me 👍

**Comment by TiuTalk** [comment]
Hi @QuintinWillison, is there an expectation around when the updated version of ably-rest (supporting faraday 1.x) will come out?

I can see the ably-ruby support for it, but my project is using ably-rest and I cannot update some other dependencies because faraday is locked on `~> 0.12` :(

Please let me know if there is anything I can do to help get this update released or at least the changes to master! 🙏🏼
