### ISSUE TITLE
1.1.3 issue with uninitialized constant Faraday::ServerError

### ISSUE THREAD

**Issue by stevepetersen** [ably/ably-ruby-rest#14]
1.1.3 with Rails fails to build correctly.  Here is the stacktrace:

$ bundle exec rake -P --trace
rake aborted!
NameError: uninitialized constant Faraday::ServerError
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-0.12.2/lib/faraday.rb:234:in `const_missing'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ably-rest-1.1.3/lib/submodules/ably-ruby/lib/ably/rest/client.rb:37:in `<class:Client>'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ably-rest-1.1.3/lib/submodules/ably-ruby/lib/ably/rest/client.rb:17:in `<module:Rest>'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ably-rest-1.1.3/lib/submodules/ably-ruby/lib/ably/rest/client.rb:9:in `<module:Ably>'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ably-rest-1.1.3/lib/submodules/ably-ruby/lib/ably/rest/client.rb:8:in `<top (required)>'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ably-rest-1.1.3/lib/submodules/ably-ruby/lib/ably/rest.rb:3:in `<top (required)>'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ably-rest-1.1.3/lib/ably-rest.rb:24:in `<top (required)>'
/Users/steve1/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/runtime.rb:66:in `require'

rolling back to 1.1.2 fixes the problem.

**Comment by TheSmartnik** [comment]
@stevepetersen thank you for reporting the problem and sorry for the slow reply. The issue has been fixed in 1.1.4 (we have a release candidate for)

**Comment by stevepetersen** [comment]
When will this be released?  It is blocking my upgrade for other gems in my system.



Steve Petersen  |  Co-founder & CTO 
Riff  |  <https://joinriff.com/>j <http://playlist.com/>oinriff.com
cell: 408-348-6765

**Comment by TheSmartnik** [comment]
@stevepetersen It's been released as a release candidate for not. Please, use `1.1.4.rc`. I'll update you as soon as we release

**Comment by owenpearson** [comment]
Hey @stevepetersen sorry for the delay in getting back to you, this has now been released in `v1.1.6`.
