### ISSUE TITLE
Faraday version mismatch with ably-ruby

### ISSUE THREAD

**Issue by thatguysimon** [ably/ably-ruby-rest#22]
Hi,
`ably-ruby` has been [recently updated](https://github.com/ably/ably-ruby/commit/9d7562872cfb869cf8e2b42182384bd21ec45d14) to support faraday 2.2.
However, since `ably-ruby` is not a dependency of `ably-ruby-rest`, but rather just a git submodule, the `faraday` version locked in `ably-ruby-rest` is still version 1. 
This makes it impossible to work with the latest version of `ably-ruby-rest`.

Thanks!

**Comment by AndyNicks** [comment]
Thanks for pointing it out @thatguysimon will fix it ASAP.
