### ISSUE TITLE
Batch publish support?

### ISSUE THREAD

**Issue by rmosolgo** [ably/ably-ruby-rest#9]
Hi! I'm using Ably's ruby gem to implement GraphQL subscriptions over Ably. 

I'd love to use the beta [batch publish](https://www.ably.io/documentation/rest-api/beta#batch-publish) feature to send updates when I have several to send at once. 

Is that supported in this gem? I didn't see it in the docs, so I thought I'd ask. Thanks!

**Comment by rmosolgo** [comment]
(Oh, I should add -- I'd also be interested in batch presence checks!)

**Comment by SimonWoolf** [comment]
It is supported via the [rest#request](https://www.ably.io/documentation/rest/usage#request) method.

If you have any further questions that are not new bugs in the client library, please use our support process, https://ably.io/support . Please do not use github issues to ask for help. Thanks

**Comment by paddybyers** [comment]
Hi,

> I'd also be interested in batch presence checks!

This is possible - see https://www.ably.io/documentation/rest/presence#batch-publish. You can query for presence on multiple channels in a single request and get a batch-mode response.

Again, in Ruby you'll need to use the `request()` method. The other limitation is that in batch mode there's no sensible way to enable paginated responses - so you're limited to getting presence on channels whose member set can be sent as a single page. That defaults to 100 entries (per channel).

**Comment by rmosolgo** [comment]
:+1: Thanks for the direction and details on that. I think it'll work out just fine, in my case I actually just care about "does this channel have any members" 👌 !
